### ISSUE TITLE
[Bug] Doesnt work with transparent background enabled

### ISSUE THREAD

**Issue by Ajaymamtora** [adriankarlen/bar.wezterm#7]
The transparent blur is not applied to the bar:

<img width="756" alt="Screenshot 2024-09-01 at 22 10 10" src="https://github.com/user-attachments/assets/c9346d88-458a-41a1-8447-92b0c047c942">

When i enabled

  macos_window_background_blur = 40,
  window_background_opacity = 0.3,

**Comment by adriankarlen** [comment]
I don't currently have access to a Mac so I can't really test this.

This is most likely due to the default colors being used (default is transparent). If you set `background` and `bg_color` of active_tab and inactive_tab in your wezterm config to your current color scheme background is the blur correctly applied?

If so, I think I'll default to that instead of transparent.

**Comment by adriankarlen** [comment]
Okay, I think this is a wezterm-bug then, perhaps you'll find better luck reporting it there?

Closing, since it is a not bug of this plugin.

Thank you, for acknowledging this.
